# Generated by Django 4.2.2 on 2023-07-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_profile_age_profile_bio_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='some string', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='some string', max_length=255, null=True),
        ),
    ]
