# Generated by Django 4.2.2 on 2023-07-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_profile_name_alter_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person1',
            field=models.CharField(default='some string', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='person2',
            field=models.CharField(default='some string', max_length=255),
        ),
    ]
