# Generated by Django 4.2.3 on 2023-07-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_remove_profile_age_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person1',
            field=models.CharField(default='some string', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='person2',
            field=models.CharField(default='some string', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.CharField(max_length=1000),
        ),
    ]
