# Generated by Django 4.2.3 on 2023-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_profile_person1_profile_person2_alter_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='some string', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person1',
            field=models.CharField(default='some string', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person2',
            field=models.CharField(default='some string', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.CharField(default='some string', max_length=1000),
        ),
    ]
