# Generated by Django 4.2.3 on 2023-07-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_alter_profile_name_alter_profile_person1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
    ]
