# Generated by Django 4.2.3 on 2023-07-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_remove_profile_name_remove_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='person2',
            field=models.CharField(default='some string', max_length=1000),
        ),
    ]
