# Generated by Django 4.2.3 on 2023-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_alter_profile_person2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='person1',
            field=models.CharField(default='some string', max_length=10000000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person2',
            field=models.CharField(default='some string', max_length=10000000),
        ),
    ]
