# Generated by Django 4.2.3 on 2023-07-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_alter_profile_person1_alter_profile_person2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='some string', max_length=100),
        ),
    ]
